language: node_js
node_js:
- 12


deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: IYgybTjAcz2Is4PKVyK4af9CkPQjMvNhjpJkrSmiWEMgd3Pul56rGkdIfqx4CpfiLfwhtd2fdXGMERysw70aYHGqXO1YSjHA2QefsZlPCmA+Zim7v8PoyakcKMlwH6epsWzUgJV13vlIutFnqxGtF/gaBRsjG1V2OmIhq5xM/lRNgAu9Sv+rPDzUp5rTYjG13ER01qnghy91CokaA9239OwrPk4Q4YhRENVjw8N0RTeccIWiF9I+bwdaITgQM5Q83iqRrCWS+Nj9fWQOSRzZFy5fwnc6T/gzyw1sRuP7B5XwjPa1hWdvc9JSR4kwutzWTU/7Q9t9uHj0ULjhkMsy+v4rWY05ml5MZAqCwp2F/waI8vQbSIaUISGjl7anCMg/CYSqUVM0Mgx12GYqj1GBs/Qqzq+jwAQFqk/WiOM6+btdOTvWmY32asIkGAuoLotC05w1eGQ3djisWRIYvJ4urGcKVACA1IisguAw2cmq4m+2rGGtMzlNSwxpgZsX8JSXB64ZIm9FpiV6+TwocG//7HRUC6jWpwbtAyJ3QtrCaeGVfSCpGcw9dTxgpbJJ6wzrMd/tKnCvNGu9QO1IOVGrbsSJFhQSeV+mXUKOzIoCfCWhEjBcwHVl4uzWTanSX2JlJ2zc2YMYWJ5qHXDLx+ph7nZhleipY8lH+vD93isH2uo=
  edge: true
  message: TravisCI deployment
cache:
  yarn: true
  directories:
  - node_modules
install:
  - yarn

script:
- yarn test
- yarn build
env:
  global:
    secure: IYgybTjAcz2Is4PKVyK4af9CkPQjMvNhjpJkrSmiWEMgd3Pul56rGkdIfqx4CpfiLfwhtd2fdXGMERysw70aYHGqXO1YSjHA2QefsZlPCmA+Zim7v8PoyakcKMlwH6epsWzUgJV13vlIutFnqxGtF/gaBRsjG1V2OmIhq5xM/lRNgAu9Sv+rPDzUp5rTYjG13ER01qnghy91CokaA9239OwrPk4Q4YhRENVjw8N0RTeccIWiF9I+bwdaITgQM5Q83iqRrCWS+Nj9fWQOSRzZFy5fwnc6T/gzyw1sRuP7B5XwjPa1hWdvc9JSR4kwutzWTU/7Q9t9uHj0ULjhkMsy+v4rWY05ml5MZAqCwp2F/waI8vQbSIaUISGjl7anCMg/CYSqUVM0Mgx12GYqj1GBs/Qqzq+jwAQFqk/WiOM6+btdOTvWmY32asIkGAuoLotC05w1eGQ3djisWRIYvJ4urGcKVACA1IisguAw2cmq4m+2rGGtMzlNSwxpgZsX8JSXB64ZIm9FpiV6+TwocG//7HRUC6jWpwbtAyJ3QtrCaeGVfSCpGcw9dTxgpbJJ6wzrMd/tKnCvNGu9QO1IOVGrbsSJFhQSeV+mXUKOzIoCfCWhEjBcwHVl4uzWTanSX2JlJ2zc2YMYWJ5qHXDLx+ph7nZhleipY8lH+vD93isH2uo=

