language: node_js

node_js:
  - 12

deploy:
  provider: firebase
  token:
    secure: "X2GL+QuK5erBzCVoQHUdHlih0Oeq33h7ZHY/iwALlB5QEttrBMEEKXccVYvVu0E4mdS9oM3jeMVMMLhVZncyBvZr54t/t5oWJe3VBvTePvbxjuN0Mpt0DWpa553c2zRWWaxB20WxkAqcA2310f5es/U2MUDaWeRmE+SD0M6P0zw0Ly+Xaz87a/ZWYul4f/IER5kbLmoC2t+Z8Z9wgg6ZGCmdtfjyctZI0BngcGdhg/wr4y7T3tacwqfeiB6hh9ifKU1drCiK9CmPYud1u+qfUUyG3fhhyV8jA0THxWEWEUHFw7IAWmn1+152db5AGiiOtpB8MUk5cHJcqz2NzzYmlRJCb7B/+77LxlcFm4S1NmqLdWfeDx3mYS5VrynkUHzCa9kj0Gn8P756AV9mV4zxcPB59jlwhyA02nn3jdZnNm+5aVgwJKg2DPVoh0OcACQfV9aZc4osEzas2GRk3zu7VC7D5FshRnohpMlikhOqJETS5k0xyL+ZBWGKcCigjCpTkDD1aOMaDdeFLNqZrwqlf+VQ4Pb+odG7AIqoJII9KFKaFcsiojt9fLFvqdpI49mW/MskAhq1Q2q0NFoHGAoddVNWDS3cmBgcvZUg/MmuM+Dhpg5yt2id29qNqR+tgVOFrXABadpDHPFgi+0gbrH5b7Fznp/x/1hnf3HU0J7DNMU="
  edge: true
  message: "TravisCI deployment"

cache:
  yarn: true
  directories:
    - 'node_modules'

script:
  - yarn test
  - yarn build