language: node_js

node_js:
  - 12

deploy:
  provider: firebase
  token:
    secure: "a3nj/lQVBUQEhezOQ08nWZekbdFr1bfWW/HXgWfcxR9/Fr9kYTp0nyoEeGAS9EujO0iobDqK2fFdNJutwLtmzcZysG9ffG/yybXvFB1Rclnhp5DRUIa3J/Vw+CNW4WwupKuoh5w8qDu6S3flcUSuOHh7MIGt4pwE5y9R/QvAAzXkgmnaygnpJcIF+ghCjGz/AAowf+vjte1nfkU1IilcPPloKVK2alARsnT8e/35Ro2qRzvuRHmJOtpKjW/8vrwBuPL3O/TTQCBiUWcPxi7FcV9tLxZ5s5UOBP+wICYaMy9K0XHO62CrdY2x6UVXZ4/MLkZpkej5pgEw6iK1fn8/5tHLklMFqGn6yoeJ3kuw7CD9QciUsJJdP8onHeHVjrBajfdRLRo3eb6OSnzdvjfLUlV15Bng6yRETD34mdhVffRP25Xa5hNTx5JjDQaIzwOeFjx740XOoMavOr5EiPyu3a34biT+o+JNA1VnWo4Fr3ftsjpJWKN2J71V59lRuuar15TiD3hoM/X0JA9wZBP1odbYynLWaaiZZEI+0/v4IBacg/0zUBPjUyVG1/w5xn7AamgkxXwNgrbywJplBudclob6j2+JXEI6uRurTkFHzSgetoKmbVu9PDFiCD/dU04Qr3P+cqey+TDkvNam8RJD8/OFkttMEVo3bXxHLyNE9/s="
  edge: true
  message: "TravisCI deployment"

cache:
  yarn: true
  directories:
    - 'node_modules'

script:
  - yarn test
  - yarn build