language: node_js
node_js:
- 12
deploy:
  provider: firebase
  token:
    secure: BNF8Kjzn6P5NiAZepYnq1POEeuOe7u0MPk/AZRBq8QNbLFhDxm8wMBLbifzi8uoLVUM6udNr6pptGRxBVpuc7ASXEP0uO+ud/djBWlhTtSU0l1d/RZoUuhpHOHjF/PFLzWvNdgsfBw9CZCX6fV691XPMBaDuRn766/G9BeXdCnIYRWn6Wv34D0aj2D2t8SaZ87IBpzeO61C+2bELk5pBdetqy4KaxZ2UG9trAp820bbuKph5XtkX8kSul8GVetVxLlcxnx25AQxiAXZ+agcsitsHJIvBPXeS3uGBncSny3xY5H8E6P4bDc/UynaUl9XTgcIavaITSG8slr9TFweVevPGRFV+Oy0CngVIivvlUcbP//dBUAzQpr7TrmPgAO3oaHWtVMNo4z9gl+N8LlJ8TeETDPDyMe6qNiSdyg6L9ZN0N3m0/9uDvvXoBtu03X8tnWscT8k3t9sl1YF3E/t1ck1/8klXHnV5e5mul4vtbyWQbgIbzfXKLLVBhx31sdsJxr6ysQWHOPVU5wi47kL6AEC5uSCSHDzikvIrFQo2oQBAHZb+UKqKCaq1v9A+2evGgX1rQW7xTy7ANJi3+h2g8yKM2qwbHAvoi5TiOUGB6bbxl6s6S67fy3Ih4wScaSNi+HEw7JXAQK8QrbkExMV+mcRdrABVb2VrtDD1xMZgiJ8=
  edge: true
  message: TravisCI deployment
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn test
- yarn build
env:
  global:
    secure: BNF8Kjzn6P5NiAZepYnq1POEeuOe7u0MPk/AZRBq8QNbLFhDxm8wMBLbifzi8uoLVUM6udNr6pptGRxBVpuc7ASXEP0uO+ud/djBWlhTtSU0l1d/RZoUuhpHOHjF/PFLzWvNdgsfBw9CZCX6fV691XPMBaDuRn766/G9BeXdCnIYRWn6Wv34D0aj2D2t8SaZ87IBpzeO61C+2bELk5pBdetqy4KaxZ2UG9trAp820bbuKph5XtkX8kSul8GVetVxLlcxnx25AQxiAXZ+agcsitsHJIvBPXeS3uGBncSny3xY5H8E6P4bDc/UynaUl9XTgcIavaITSG8slr9TFweVevPGRFV+Oy0CngVIivvlUcbP//dBUAzQpr7TrmPgAO3oaHWtVMNo4z9gl+N8LlJ8TeETDPDyMe6qNiSdyg6L9ZN0N3m0/9uDvvXoBtu03X8tnWscT8k3t9sl1YF3E/t1ck1/8klXHnV5e5mul4vtbyWQbgIbzfXKLLVBhx31sdsJxr6ysQWHOPVU5wi47kL6AEC5uSCSHDzikvIrFQo2oQBAHZb+UKqKCaq1v9A+2evGgX1rQW7xTy7ANJi3+h2g8yKM2qwbHAvoi5TiOUGB6bbxl6s6S67fy3Ih4wScaSNi+HEw7JXAQK8QrbkExMV+mcRdrABVb2VrtDD1xMZgiJ8=
